const languages = [
['HINDI','जन्मदिन की बहुत-बहुत शुभकामनाएँ, अनिशा! ❤️<br>तुम्हारी ज़िंदगी हमेशा ढेर सारी खुशियों, नई यादों और मुस्कुराहटों से भरी रहे। हमेशा खुश रहो! 🎂✨','Wishing you lots of happiness! May your life always be filled with beautiful memories and countless reasons to smile.'],
['BENGALI','শুভ জন্মদিন, অনিশা! ❤️<br>তোমার জীবনটা আনন্দ, সুন্দর মুহূর্ত আর অসংখ্য হাসিতে ভরে উঠুক। তোমার সব ইচ্ছে পূরণ হোক! 🎂✨','May your life be filled with joy, beautiful moments and endless laughter. May all your wishes come true!'],
['TAMIL','இனிய பிறந்தநாள் வாழ்த்துகள், அனிஷா! ❤️<br>உன் வாழ்க்கை இனிய அனுபவங்களாலும், மகிழ்ச்சியான நாட்களாலும், மறக்க முடியாத நினைவுகளாலும் நிறைந்திருக்கட்டும்! 🎂🌸','May your life be filled with wonderful experiences, happy days and unforgettable memories!'],
['TELUGU','పుట్టినరోజు శుభాకాంక్షలు, అనిషా! ❤️<br>నీ జీవితం కొత్త అవకాశాలు, మంచి జ్ఞాపకాలు, నవ్వులు మరియు విజయాలతో నిండిపోవాలని కోరుకుంటున్నాను. 🎂✨','May your life be filled with new opportunities, beautiful memories, laughter and success!'],
['MARATHI','वाढदिवसाच्या मनापासून शुभेच्छा, अनिशा! ❤️<br>तुझं आयुष्य आनंद, यश आणि भरपूर सुंदर आठवणींनी भरलेलं असो. तुझ्या चेहऱ्यावरचं हसू असंच कायम राहो! 🎂✨','May your life be filled with happiness, success and beautiful memories. May your smile always remain!'],
['GUJARATI','જન્મદિવસની દિલથી ખૂબ ખૂબ શુભેચ્છાઓ, અનિશા! ❤️<br>તારું જીવન નવી ખુશીઓ, નવી તકો અને ઘણી બધી યાદગાર પળોથી ભરેલું રહે. તારા બધા સપના સાકાર થાય! 🎂✨','May your life be full of new happiness, new opportunities and unforgettable moments. May all your dreams come true!'],
['KANNADA','ಹುಟ್ಟುಹಬ್ಬದ ಹಾರ್ದಿಕ ಶುಭಾಶಯಗಳು, ಅನಿಷಾ! ❤️<br>ನಿನ್ನ ಜೀವನವು ನಗು, ಸಂತೋಷ, ಯಶಸ್ಸು ಮತ್ತು ಮರೆಯಲಾಗದ ಸುಂದರ ಕ್ಷಣಗಳಿಂದ ತುಂಬಿರಲಿ. 🎂✨','May your life be filled with laughter, happiness, success and beautiful moments you will never forget!'],
['MALAYALAM','ജന്മദിനാശംസകൾ, അനിഷാ! ❤️<br>നിന്റെ ജീവിതം ഒരുപാട് സന്തോഷങ്ങളും പുതിയ അനുഭവങ്ങളും മനോഹരമായ ഓർമ്മകളും കൊണ്ട് നിറയട്ടെ. എപ്പോഴും പുഞ്ചിരിച്ചുകൊണ്ടിരിക്കൂ! 🎂✨','May your life be filled with lots of happiness, new experiences and beautiful memories. Keep smiling always!'],
['PUNJABI','ਜਨਮਦਿਨ ਦੀਆਂ ਲੱਖ-ਲੱਖ ਵਧਾਈਆਂ, ਅਨੀਸ਼ਾ! ❤️<br>ਤੇਰੀ ਜ਼ਿੰਦਗੀ ਖੁਸ਼ੀਆਂ, ਕਾਮਯਾਬੀਆਂ ਤੇ ਬਹੁਤ ਸਾਰੇ ਯਾਦਗਾਰ ਪਲਾਂ ਨਾਲ ਭਰੀ ਰਹੇ। ਹਮੇਸ਼ਾ ਏਦਾਂ ਹੀ ਹੱਸਦੀ ਰਹੀਂ! 🎂✨','Many many happy birthday wishes! May your life be full of happiness, success and memorable moments. Keep laughing like this!'],
['ODIA','ଜନ୍ମଦିନର ଅନେକ ଅନେକ ଶୁଭେଚ୍ଛା, ଅନିଶା! ❤️<br>ତୁମର ଜୀବନ ନୂଆ ସ୍ୱପ୍ନ, ସଫଳତା ଏବଂ ଅନେକ ସୁନ୍ଦର ସ୍ମୃତିରେ ଭରିଯାଉ। 🎂✨','May your life be filled with new dreams, success and many beautiful memories!'],
['ASSAMESE','জন্মদিনৰ আন্তৰিক শুভেচ্ছা, অনিশা! ❤️<br>তোমাৰ জীৱন সুখ, সফলতা আৰু সুন্দৰ অভিজ্ঞতাৰে ভৰি পৰক। সদায় এনেকৈয়ে হাঁহি থাকা! 🎂✨','May your life be filled with happiness, success and wonderful experiences. Keep smiling!'],
['NEPALI','जन्मदिनको धेरै धेरै शुभकामना, अनिशा! ❤️<br>तिम्रो जीवन नयाँ सपना, सुन्दर अवसर र धेरै खुसीका पलहरूले भरिएको होस्। सधैं यस्तै मुस्कुराइरहनू! 🎂✨','May your life be filled with new dreams, beautiful opportunities and many happy moments. Keep smiling!'],
['KONKANI','जन्मदिसाच्या खूब खूब परबीं, अनिशा! ❤️<br>तुजें आयुश्य सुखान, येसान आनी सुंदर यादिंनी भरिल्लें आसूं. तुजो हांसो सदांच असोच रावूं! 🎂✨','May your life be filled with happiness, success and beautiful memories. May your smile always stay the same!'],
['BHOJPURI','जन्मदिन के ढेर सारा शुभकामना, अनिशा! ❤️<br>तोहार जिनगी खुशियन, सफलता आ नया-नया खूबसूरत याद से भरल रहे। तोहार हर मनोकामना पूरा होखे आ तू हमेशा हँसत रहऽ! 🎂✨','May your life be filled with happiness, success and beautiful new memories. May all your wishes come true and may you always keep smiling!'],
['SANSKRIT','जन्मदिवसस्य हार्दिकाः शुभकामनाः, अनिशा! ❤️<br>तव जीवनं सुखेन, यशसा, आनन्देन च परिपूर्णं भवतु। तव सर्वे मनोरथाः सफलाः भवन्तु। 🎂✨','May your life be filled with happiness, success and joy. May all your wishes and aspirations be fulfilled!'],
['MAITHILI','जन्मदिनक बहुत-बहुत शुभकामना, अनिशा! ❤️<br>अहाँक जीवन नव खुशी, सफलता आ सुन्दर अनुभव सँ भरल रहय। अहाँक सभ सपना पूरा हो! 🎂✨','May your life be filled with new happiness, success and beautiful experiences. May all your dreams come true!'],
['HARYANVI','जन्मदिन की घणी-घणी बधाई, अनीशा! ❤️<br>तेरी जिंदगी खुशियां, तरक्की और बढ़िया-बढ़िया यादां तै भरती रहै। जो चाहै वो मिलै, और तेरी हंसी हमेशा ऐसे ही चलती रहै! 😂🎂✨','Many happy birthday wishes! May your life be filled with happiness, growth and lots of great memories. May you get everything you wish for, and may your laughter always stay just like this!'],
['RAJASTHANI','जन्मदिन री घणी-घणी बधाइयाँ, अनीशा! ❤️<br>थारी जिंदगी खुशियाँ, तरक्की अर यादगार पलां सूं भरपूर रहै। सदा हँसती रहजो! 🎂✨','Many happy birthday wishes! May your life be full of happiness, growth and memorable moments. Keep smiling always!'],
['CHHATTISGARHI','जन्मदिन के ढेर सारी बधई हो, अनीशा! ❤️<br>तोर जिनगी खुशी, सफलता अउ सुंदर याद मन ले भर जावय। हमेशा मुस्कुरात रहिबे! 🎂✨','Lots of birthday wishes! May your life be filled with happiness, success and wonderful memories. Always keep smiling!'],
['MEITEI (MANIPURI)','ꯄꯣꯠꯊꯣꯛꯄ ꯅꯨꯃꯤꯠꯇ ꯊꯥꯒꯠꯆꯔꯤ, ꯑꯅꯤꯁꯥ! ❤️<br>ꯅꯍꯥꯛꯀꯤ ꯄꯨꯟꯁꯤ ꯑꯁꯤ ꯁꯨꯈ, ꯐꯖꯕ ꯃꯇꯝꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯅꯨꯃꯤꯠ ꯃꯇꯝꯁꯤꯡꯅ ꯄꯨꯟꯁꯤ ꯐꯖꯕ ꯑꯣꯏꯔꯁꯤ! 🎂✨','May your life be filled with happiness, beautiful experiences and many wonderful days ahead!'],
['SANTALI','ᱡᱟᱱᱟᱢ ᱢᱟᱦᱟ ᱥᱟᱹᱜᱟᱹᱭ ᱦᱚᱪᱚᱜᱼᱟ, ᱟᱱᱤᱥᱟ! ❤️<br>ᱟᱢᱟᱜ ᱡᱤᱣᱤ ᱥᱟᱹᱨᱤ ᱠᱷᱩᱥᱤ ᱟᱨ ᱥᱩᱱᱫᱚᱨ ᱥᱢᱨᱤᱛᱤ ᱠᱚ ᱥᱟᱶ ᱫᱟᱲᱟᱭ ᱢᱮᱛᱟᱜ ᱦᱚᱪᱚᱜᱼᱟ। 🎂✨','May your life bring you lots of happiness and beautiful memories!'],
['BODO','जन्मदिननि बुंफार जौगोन, अनिशा! ❤️<br>नोंनि जिन्दागीआ सुख, हांख्रि आरो गोसोनि समावफोरजों आबुं जाबाय। नोंनि मोननि साननायफोर फुरनाय जाथों! 🎂✨','May your life be filled with happiness, laughter and wonderful moments. May the things you wish for come true!'],
['MIZO','Pian ni lawm takin, Anisha! ❤️<br>I nun hi hlimna, lawmna leh thil thar zirna hun nuam tak takte-in a khat se rawh se. I duhthusam zawng zawngte chu a takin lo thleng rawh se! 🎂✨','May your life be filled with happiness, joyful experiences and wonderful new things to discover. May your dreams come true!'],
['KHASI','Ka sngi kha kaba kmen, Anisha! ❤️<br>Nga kyrmen ba ka jingim jong phi kan dap da ka jingkmen, ka jingjop bad ki jingkynmaw kiba itynnad. To phi long suk bad kmen ha man la ka sngi! 🎂✨','May your life be filled with happiness, success and beautiful memories. May you be peaceful and happy every day!'],
['TULU','Puttudina da appe, Anisha! ❤️<br>Ninna jeevana santosha, geluvu mattu sundara nenapulu inda tumbundu ijji. Ninna ella kanasulu neraverodu! 🎂✨','May your life be filled with happiness, success and beautiful memories. May all your dreams come true!'],
['KULLAVI 🏔️❤️','जन्मदिन री घणी बधाई अनीशा! ❤️<br>तेरी जिंदगी सदा खुशियां सूं भरी रहै। भगवान तैं हर सुख दे, तेरे सारे काम सफल होन, अर तू सदा हंसदी-खेलदी रहै। 🎂❤️','Happy Birthday, Anisha! May your life always be filled with happiness. May God bless you with every happiness, may all your efforts succeed, and may you always stay cheerful and smiling.']
];
const opening=`🎂❤️ HAPPY BIRTHDAY, ANISHA! ❤️🎂<br><br>Okay… so it's your birthday. 😂<br><br>And because you're one of my bestest friends, I couldn't just send you a normal “Happy Birthday” and disappear. 😌<br><br>So I did something slightly stupid… 😂<br><br>I collected 26 birthday wishes in 26 different Indian languages — because apparently one birthday wish wasn't enough. 🇮🇳🌍<br><br>The funniest part? I can't even read most of these properly. 💀😂<br><br>So if anything is pronounced horribly, just appreciate the effort. 😂<br><br>Anyway…<br><br>26 wishes. 26 languages. One very special best friend. ❤️<br><br>Let's see how far you make it. 😂👇`;
const dream=`✨🇮🇳 AND MAYBE THIS IS JUST THE BEGINNING… 🇮🇳✨<br><br>You always dream about becoming an influencer and making your name reach people far beyond where you are today.<br><br>So I thought… why not give you a tiny preview of that dream? 😂❤️<br><br>Today, your birthday wishes travelled across India — from language to language, from state to state. 🇮🇳<br><br>26 wishes.<br>26 different languages.<br>One dream.<br><br>Maybe one day, millions of people will know your name, follow your journey, and wish you on your birthday from every corner of the country.<br><br>And when that day comes, remember…<br>This was your little “All-India fanbase” rehearsal. 😂🇮🇳❤️<br><br>I genuinely hope you chase that dream, make it happen, and become exactly the influencer you've always imagined yourself becoming.<br><br>Your dream deserves to come true.<br>And when it does, I'll be there saying — “I told you so.” 😂🫶<br><br>Happy Birthday, future influencer. 🎂✨🇮🇳`;
const closing=`❤️ AND FINALLY…<br><br>Okay, you actually made it to the end. 😂<br><br>26 wishes.<br>26 languages.<br>And probably at least 26 times you wondered, “What the hell is this guy doing?” 😂<br><br>I know I could've just said “Happy Birthday” like a normal person…<br>But you're not exactly a normal friend to me, so a normal birthday wish would've been too boring. ❤️<br><br>No matter how far apart we are, I hope today reminds you that there is someone sitting miles away who genuinely wishes the absolute best for you.<br><br>Keep smiling. Keep being your crazy self. Keep making stupid memories. 😂<br><br>And most importantly, never forget how loved and appreciated you are by the people who have you in their lives.<br><br>Happy Birthday once again, Anisha. 🎂❤️<br><br>Have the best birthday ever, bestest friend. 🫶`;
